### ISSUE TITLE
Unable to create a schedule with concurrencyPolicy = FORBID on DC/OS 1.8.4

### ISSUE THREAD

**Issue by lubomir-haralampiev** [dcos/metronome#100] opened 2016-10-21 10:34 UTC
I'm unable to create a schedule which doesn't start a new job before the old one has finished.

I'm using the REST API of DC/OS 1.8.4 as follows:
`POST /service/metronome/v1/jobs/<my-job>/schedules`

```
{
    "id": "default",
    "enabled": true,
    "cron": "*/5 * * * *",
    "concurrencyPolicy": "FORBID"
}
```

But I'm getting the following error:
`{"message":"No enum constant dcos.metronome.Protos.JobSpec.ScheduleSpec.ConcurrencyPolicy.FORBID"}`

What am I missing?

**Comment by tobilg** [comment] 2016-10-21 10:38
Having a look at the protobuf, it seems that `FORBID` is not implemented: https://github.com/dcos/metronome/blob/master/jobs/src/main/protobuf/metronome.proto#L82

**Comment by drewrobb** [comment] 2016-11-09 21:06
`REPLACE` is also defined in the job spec but not implemented

**Comment by janisz** [comment] 2016-11-15 22:39
What's more `FORBID` is [default concurrency policy](https://github.com/dcos/metronome/blob/4336d5b15cdd19be4088cd0d68268c5f9b96fc4d/jobs/src/main/scala/dcos/metronome/model/ScheduleSpec.scala#L28). Maybe this feature works only in Enterprise DCOS version.

**Comment by aquamatthias** [comment] 2016-11-28 08:50
The only implemented policy in Metronome currently is `Allow`. 
A validation rule is needed to fail for any other value.

**Comment by matt-deboer** [comment] 2017-01-25 21:25
Could you please update the [docs](https://dcos.github.io/metronome/docs/generated/api.html#v0_scheduled_jobs_post) so we (paying enterprise customers) don't have to discover it the hard way?

**Comment by sascala** [comment] 2017-01-25 22:02
https://github.com/dcos/dcos-docs/pull/867

@kensipe -- was this supposed to be fixed in the latest CLI version, or is my memory bad?

**Comment by kensipe** [comment] 2017-01-25 22:12
@sascala the issue listed here isn't a CLI thing...   The issue is around we have policies that are not implemented which are not documented that they are not implemented.   There are 2 places this should likely go... 1) the [generated docs from the RAML](https://dcos.github.io/metronome/docs/generated/api.html#v0_scheduled_jobs_post) and our documentation.   

@matt-deboer thanks for the heads up... I will get a PR muy pronto.

**Comment by aquamatthias** [comment] 2017-01-26 10:27
PR is here: #121

**Closed** 2017-01-26 13:05 UTC
Labels: enhancement, in progress

**Comment by kensipe** [comment] 2017-01-26 14:51
@matt-deboer the fix is underway and should be pushed soon:  https://github.com/dcos/metronome/commit/50c938c46c676ce098a3b9758f3d0612881cef01
